<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleTracker.DAL\SimpleTracker.DAL.csproj" />
    <ProjectReference Include="..\SimpleTracker.DTO\SimpleTracker.DTO.csproj" />
    <ProjectReference Include="..\SimpleTracker.Utility\SimpleTracker.Utility.csproj" />
  </ItemGroup>

</Project>
